# specify a base image
FROM node:14

WORKDIR /usr/app

# Install some dependencies
# copy package.json file in the current working directory then npm install 
# if package.json file will change then only npm i will trigger or any above steps changes 
# then npm i will trigger
COPY ./package.json ./
RUN npm install 
# after copy all files to current work dir
COPY ./ ./

# Default command
CMD ["npm","start"]