const countries = [
  { value: "1", displayValue: "Afghanistan" },
  { value: "2", displayValue: "Albania" },
  { value: "3", displayValue: "Algeria" },
  { value: "4", displayValue: "American Samoa" },
  { value: "5", displayValue: "Angola" },
  { value: "6", displayValue: "Anguilla" },
  { value: "7", displayValue: "Antartica" },
  { value: "8", displayValue: "Antigua and Barbuda" },
  { value: "9", displayValue: "Argentina" },
  { value: "10", displayValue: "Armenia" },
  { value: "11", displayValue: "Aruba" },
  { value: "12", displayValue: "Ashmore and Cartier Island" },
  { value: "13", displayValue: "Australia" },
  { value: "14", displayValue: "Austria" },
  { value: "15", displayValue: "Azerbaijan" },
  { value: "16", displayValue: "Bahamas" },
  { value: "17", displayValue: "Bahrain" },
  { value: "18", displayValue: "Bangladesh" },
  { value: "19", displayValue: "Barbados" },
  { value: "20", displayValue: "Belarus" },
  { value: "21", displayValue: "Belgium" },
  { value: "22", displayValue: "Belize" },
  { value: "23", displayValue: "Benin" },
  { value: "24", displayValue: "Bermuda" },
  { value: "25", displayValue: "Bhutan" },
  { value: "26", displayValue: "Bolivia" },
  { value: "27", displayValue: "Bosnia and Herzegovina" },
  { value: "28", displayValue: "Botswana" },
  { value: "29", displayValue: "Brazil" },
  { value: "30", displayValue: "British Virgin Islands" },
  { value: "31", displayValue: "Brunei" },
  { value: "32", displayValue: "Bulgaria" },
  { value: "33", displayValue: "Burkina Faso" },
  { value: "34", displayValue: "Burma" },
  { value: "35", displayValue: "Burundi" },
  { value: "36", displayValue: "Cambodia" },
  { value: "37", displayValue: "Cameroon" },
  { value: "38", displayValue: "Canada" },
  { value: "39", displayValue: "Cabo Verde" },
  { value: "40", displayValue: "Cayman Islands" },
  { value: "41", displayValue: "Central African Republic" },
  { value: "42", displayValue: "Chad" },
  { value: "43", displayValue: "Chile" },
  { value: "44", displayValue: "China" },
  { value: "45", displayValue: "Christmas Island" },
  { value: "46", displayValue: "Clipperton Island" },
  { value: "47", displayValue: "Cocos (Keeling) Islands" },
  { value: "48", displayValue: "Colombia" },
  { value: "49", displayValue: "Comoros" },
  { value: "50", displayValue: "Congo, Democratic Republic of the" },
  { value: "51", displayValue: "Congo, Republic of the" },
  { value: "52", displayValue: "Cook Islands" },
  { value: "53", displayValue: "Costa Rica" },
  { value: "54", displayValue: "Cote dIvoire" },
  { value: "55", displayValue: "Croatia" },
  { value: "56", displayValue: "Cuba" },
  { value: "57", displayValue: "Cyprus" },
  { value: "58", displayValue: "Czechia" },
  { value: "59", displayValue: "Denmark" },
  { value: "60", displayValue: "Djibouti" },
  { value: "61", displayValue: "Dominica" },
  { value: "62", displayValue: "Dominican Republic" },
  { value: "63", displayValue: "Ecuador" },
  { value: "64", displayValue: "Egypt" },
  { value: "65", displayValue: "El Salvador" },
  { value: "66", displayValue: "Equatorial Guinea" },
  { value: "67", displayValue: "Eritrea" },
  { value: "68", displayValue: "Estonia" },
  { value: "69", displayValue: "Ethiopia" },
  { value: "70", displayValue: "Europa Island" },
  { value: "71", displayValue: "Falkland Islands (Islas Malvinas)" },
  { value: "72", displayValue: "Faroe Islands" },
  { value: "73", displayValue: "Fiji" },
  { value: "74", displayValue: "Finland" },
  { value: "75", displayValue: "France" },
  { value: "76", displayValue: "French Guiana" },
  { value: "77", displayValue: "French Polynesia" },
  { value: "78", displayValue: "French Southern and Antarctic Lands" },
  { value: "79", displayValue: "Gabon" },
  { value: "80", displayValue: "Gambia, The" },
  { value: "81", displayValue: "Gaza Strip" },
  { value: "82", displayValue: "Georgia" },
  { value: "83", displayValue: "Germany" },
  { value: "84", displayValue: "Ghana" },
  { value: "85", displayValue: "Gibraltar" },
  { value: "86", displayValue: "Glorioso Islands" },
  { value: "87", displayValue: "Greece" },
  { value: "88", displayValue: "Greenland" },
  { value: "89", displayValue: "Grenada" },
  { value: "90", displayValue: "Guadeloupe" },
  { value: "91", displayValue: "Guam" },
  { value: "92", displayValue: "Guatemala" },
  { value: "93", displayValue: "Guernsey" },
  { value: "94", displayValue: "Guinea" },
  { value: "95", displayValue: "Guinea-Bissau" },
  { value: "96", displayValue: "Guyana" },
  { value: "97", displayValue: "Haiti" },
  { value: "98", displayValue: "Heard Island and McDonald Islands" },
  { value: "99", displayValue: "Holy See (Vatican City)" },
  { value: "100", displayValue: "Honduras" },
  { value: "101", displayValue: "Hong Kong" },
  { value: "102", displayValue: "Howland Island" },
  { value: "103", displayValue: "Hungary" },
  { value: "104", displayValue: "Iceland" },
  { value: "105", displayValue: "India" },
  { value: "106", displayValue: "Indonesia" },
  { value: "107", displayValue: "Iran" },
  { value: "108", displayValue: "Iraq" },
  { value: "109", displayValue: "Ireland" },
  { value: "110", displayValue: "Ireland, Northern" },
  { value: "111", displayValue: "Israel" },
  { value: "112", displayValue: "Italy" },
  { value: "113", displayValue: "Jamaica" },
  { value: "114", displayValue: "Jan Mayen" },
  { value: "115", displayValue: "Japan" },
  { value: "116", displayValue: "Jarvis Island" },
  { value: "117", displayValue: "Jersey" },
  { value: "118", displayValue: "Johnston Atoll" },
  { value: "119", displayValue: "Jordan" },
  { value: "120", displayValue: "Juan de Nova Island" },
  { value: "121", displayValue: "Kazakhstan" },
  { value: "122", displayValue: "Kenya" },
  { value: "123", displayValue: "Kiribati" },
  { value: "124", displayValue: "Korea, North" },
  { value: "125", displayValue: "Korea, South" },
  { value: "126", displayValue: "Kuwait" },
  { value: "127", displayValue: "Kyrgyzstan" },
  { value: "128", displayValue: "Laos" },
  { value: "129", displayValue: "Latvia" },
  { value: "130", displayValue: "Lebanon" },
  { value: "131", displayValue: "Lesotho" },
  { value: "132", displayValue: "Liberia" },
  { value: "133", displayValue: "Libya" },
  { value: "134", displayValue: "Liechtenstein" },
  { value: "135", displayValue: "Lithuania" },
  { value: "136", displayValue: "Luxembourg" },
  { value: "137", displayValue: "Macau" },
  { value: "138", displayValue: "North Macedonia" },
  { value: "139", displayValue: "Madagascar" },
  { value: "140", displayValue: "Malawi" },
  { value: "141", displayValue: "Malaysia" },
  { value: "142", displayValue: "Maldives" },
  { value: "143", displayValue: "Mali" },
  { value: "144", displayValue: "Malta" },
  { value: "145", displayValue: "Man, Isle of" },
  { value: "146", displayValue: "Marshall Islands" },
  { value: "147", displayValue: "Martinique" },
  { value: "148", displayValue: "Mauritania" },
  { value: "149", displayValue: "Mauritius" },
  { value: "150", displayValue: "Mayotte" },
  { value: "151", displayValue: "Mexico" },
  { value: "152", displayValue: "Micronesia, Federated States of" },
  { value: "153", displayValue: "Midway Islands" },
  { value: "154", displayValue: "Moldova" },
  { value: "155", displayValue: "Monaco" },
  { value: "156", displayValue: "Mongolia" },
  { value: "157", displayValue: "Montserrat" },
  { value: "158", displayValue: "Morocco" },
  { value: "159", displayValue: "Mozambique" },
  { value: "160", displayValue: "Namibia" },
  { value: "161", displayValue: "Nauru" },
  { value: "162", displayValue: "Nepal" },
  { value: "163", displayValue: "Netherlands" },
  { value: "164", displayValue: "Netherlands Antilles" },
  { value: "165", displayValue: "New Caledonia" },
  { value: "166", displayValue: "New Zealand" },
  { value: "167", displayValue: "Nicaragua" },
  { value: "168", displayValue: "Niger" },
  { value: "169", displayValue: "Nigeria" },
  { value: "170", displayValue: "Niue" },
  { value: "171", displayValue: "Norfolk Island" },
  { value: "172", displayValue: "Northern Mariana Islands" },
  { value: "173", displayValue: "Norway" },
  { value: "174", displayValue: "Oman" },
  { value: "175", displayValue: "Pakistan" },
  { value: "176", displayValue: "Palau" },
  { value: "177", displayValue: "Panama" },
  { value: "178", displayValue: "Papua New Guinea" },
  { value: "179", displayValue: "Paraguay" },
  { value: "180", displayValue: "Peru" },
  { value: "181", displayValue: "Philippines" },
  { value: "182", displayValue: "Pitcaim Islands" },
  { value: "183", displayValue: "Poland" },
  { value: "184", displayValue: "Portugal" },
  { value: "185", displayValue: "Puerto Rico" },
  { value: "186", displayValue: "Qatar" },
  { value: "187", displayValue: "Reunion" },
  { value: "188", displayValue: "Romainia" },
  { value: "189", displayValue: "Russia" },
  { value: "190", displayValue: "Rwanda" },
  { value: "191", displayValue: "Saint Helena" },
  { value: "192", displayValue: "Saint Kitts and Nevis" },
  { value: "193", displayValue: "Saint Lucia" },
  { value: "194", displayValue: "Saint Pierre and Miquelon" },
  { value: "195", displayValue: "Saint Vincent and the Grenadines" },
  { value: "196", displayValue: "Samoa" },
  { value: "197", displayValue: "San Marino" },
  { value: "198", displayValue: "Sao Tome and Principe" },
  { value: "199", displayValue: "Saudi Arabia" },
  { value: "200", displayValue: "Scotland" },
  { value: "201", displayValue: "Senegal" },
  { value: "202", displayValue: "Seychelles" },
  { value: "203", displayValue: "Sierra Leone" },
  { value: "204", displayValue: "Singapore" },
  { value: "205", displayValue: "Slovakia" },
  { value: "206", displayValue: "Slovenia" },
  { value: "207", displayValue: "Solomon Islands" },
  { value: "208", displayValue: "Somalia" },
  { value: "209", displayValue: "South Africa" },
  { value: "210", displayValue: "South Georgia and South Sandwich Islands" },
  { value: "211", displayValue: "Spain" },
  { value: "212", displayValue: "Spratly Islands" },
  { value: "213", displayValue: "Sri Lanka" },
  { value: "214", displayValue: "Sudan" },
  { value: "215", displayValue: "Suriname" },
  { value: "216", displayValue: "Svalbard" },
  { value: "217", displayValue: "eSwatini" },
  { value: "218", displayValue: "Sweden" },
  { value: "219", displayValue: "Switzerland" },
  { value: "220", displayValue: "Syria" },
  { value: "221", displayValue: "Taiwan" },
  { value: "222", displayValue: "Tajikistan" },
  { value: "223", displayValue: "Tanzania" },
  { value: "224", displayValue: "Thailand" },
  { value: "225", displayValue: "Tobago" },
  { value: "226", displayValue: "Toga" },
  { value: "227", displayValue: "Tokelau" },
  { value: "228", displayValue: "Tonga" },
  { value: "229", displayValue: "Trinidad" },
  { value: "230", displayValue: "Tunisia" },
  { value: "231", displayValue: "Turkey" },
  { value: "232", displayValue: "Turkmenistan" },
  { value: "233", displayValue: "Tuvalu" },
  { value: "234", displayValue: "Uganda" },
  { value: "235", displayValue: "Ukraine" },
  { value: "236", displayValue: "United Arab Emirates" },
  { value: "237", displayValue: "United Kingdom" },
  { value: "238", displayValue: "Uruguay" },
  { value: "239", displayValue: "USA" },
  { value: "240", displayValue: "Uzbekistan" },
  { value: "241", displayValue: "Vanuatu" },
  { value: "242", displayValue: "Venezuela" },
  { value: "243", displayValue: "Vietnam" },
  { value: "244", displayValue: "Virgin Islands" },
  { value: "245", displayValue: "Wales" },
  { value: "246", displayValue: "Wallis and Futuna" },
  { value: "247", displayValue: "West Bank" },
  { value: "248", displayValue: "Western Sahara" },
  { value: "249", displayValue: "Yemen" },
  { value: "251", displayValue: "Zambia" },
  { value: "252", displayValue: "Zimbabwe" },
  { value: "284210000", displayValue: "Kosovo" },
  { value: "284210002", displayValue: "Montenegro" },
  { value: "284210001", displayValue: "Serbia" },
  { value: "284210003", displayValue: "Timor-Leste" },
  { value: "100000000", displayValue: "Togo" },
];

export default countries;
