import React from "react";
import AccountBoxIcon from "@material-ui/icons/AccountBox";
import PhoneIcon from "@material-ui/icons/Phone";
import PublicIcon from "@material-ui/icons/Public";
import StreetviewIcon from "@material-ui/icons/Streetview";
import LocationCityIcon from "@material-ui/icons/LocationCity";
import AddLocationIcon from "@material-ui/icons/AddLocation";
import PermIdentityIcon from "@material-ui/icons/PermIdentity";
import PermContactCalendarIcon from "@material-ui/icons/PermContactCalendar";
// import CardMembershipIcon from "@material-ui/icons/CardMembership";
import AssignmentIcon from "@material-ui/icons/Assignment";
import MailOutlineIcon from "@material-ui/icons/MailOutline";
// import PeopleAltIcon from "@material-ui/icons/PeopleAlt";
// import AccountBalanceIcon from "@material-ui/icons/AccountBalance";
import CardGiftcardIcon from "@material-ui/icons/CardGiftcard";
import BusinessIcon from "@material-ui/icons/Business";
import WorkIcon from "@material-ui/icons/Work";
import DnsIcon from "@material-ui/icons/Dns";
import SchoolIcon from "@material-ui/icons/School";
import Country from "./countryList";
import YearList from "components/Prospective/years";
import SchoolCoutry from "components/Prospective/schoolCountry";

let FormData = {
  personalInformation: {
    ses_applicant: {
      elementType: "input",
      elementConfig: {
        type: "text",
        label: "Applicant ID",
        autoComplete: "Applicant ID",
        name: "ses_applicant",
        disabled: true,
        fullWidth: true,
      },
      maxLength: 50,
      icon: <PermContactCalendarIcon style={{ color: "#959595" }} />,
      value: "",
    },
    firstname: {
      elementType: "input",
      elementConfig: {
        type: "text",
        autoFocus: true,
        label: "First Name",
        autoComplete: "first-name",
        name: "firstname",
        required: true,
        fullWidth: true,
      },
      maxLength: 50,
      isValid: false,
      errorMessage: "First Name can't be blank",
      icon: <AccountBoxIcon style={{ color: "#959595" }} />,
      value: "",
    },
    middlename: {
      elementType: "input",
      elementConfig: {
        type: "text",
        label: "Middle Name",
        autoComplete: "middle-name",
        name: "middlename",
        fullWidth: true,
      },
      maxLength: 50,
      icon: <AccountBoxIcon style={{ color: "#959595" }} />,
      value: "",
    },
    lastname: {
      elementType: "input",
      elementConfig: {
        type: "text",
        label: "Last Name",
        autoComplete: "last-name",
        name: "lastname",
        required: true,
        fullWidth: true,
      },
      maxLength: 50,
      isValid: false,
      errorMessage: "Last Name can't be blank",
      icon: <AccountBoxIcon style={{ color: "#959595" }} />,
      value: "",
    },
    eslsca_arabicname: {
      elementType: "input",
      elementConfig: {
        type: "text",
        label: "Arabic Name",
        autoComplete: "arabic-name",
        name: "eslsca_arabicname",
        fullWidth: true,
        required: true,
      },
      isValid: false,
      errorMessage: "Arabic Name can't be blank",
      maxLength: 150,
      icon: <AccountBoxIcon style={{ color: "#959595" }} />,
      value: "",
    },
    gendercode: {
      elementType: "select",
      elementConfig: {
        label: "Gender *",
        required: true,
        options: [
          { value: 1, displayValue: "Male" },
          { value: 2, displayValue: "Female" },
        ],
        name: "gendercode",
      },
      value: 1,
    },
    governmentid: {
      elementType: "input",
      elementConfig: {
        type: "text",
        label: "ID/Passport Number",
        autoComplete: "goverment-id",
        name: "governmentid",
        fullWidth: true,
      },
      maxLength: 50,
      icon: <PermIdentityIcon style={{ color: "#959595" }} />,
      value: "",
    },

    birthdate: {
      elementType: "date",
      elementConfig: {
        label: "Date of Birth* (DD/MM/YYYY)",
        name: "birthdate",
        id: "time-picker",
        fullWidth: true,
      },
      value: "",
    },
    ses_birthcountry: {
      elementType: "input",
      elementConfig: {
        type: "text",
        label: "Country of Birth",
        autoComplete: "birthdate",
        name: "ses_birthcountry",
        required: true,
        fullWidth: true,
      },
      maxLength: 30,
      isValid: false,
      errorMessage: "Country of Birth can't be blank",
      icon: <PublicIcon style={{ color: "#959595" }} />,
      value: "",
    },
    // ses_birthcity: {
    //   elementType: "input",
    //   elementConfig: {
    //     type: "text",
    //     label: "City of Birth",
    //     autoComplete: "birthdate",
    //     name: "ses_birthcity",
    //     required: true,
    //     fullWidth: true,
    //   },
    //   maxLength: 30,
    //   isValid: false,
    //   errorMessage: "City of Birth can't be blank",
    //   icon: <LocationCityIcon style={{ color: "#959595" }} />,
    //   value: "",
    // },
    ses_nationality: {
      elementType: "select",
      elementConfig: {
        label: "Nationality*",
        options: Country,
        name: "ses_nationality",
      },
      value: 239,
    },
    eslsca_dualnationality: {
      elementType: "select",
      elementConfig: {
        label: "Dual Nationality",
        options: Country,
        name: "eslsca_dualnationality",
      },
      value: 239,
    },
    eslsca_applicantsource: {
      elementType: "select",
      elementConfig: {
        label: "How did you find out about ESLSCA ?",
        options: [
          { value: "991490000", displayValue: "ESLSCA Alumni" },
          { value: "991490001", displayValue: "ESLSCA Events" },
          { value: "991490002", displayValue: "Twitter" },
          { value: "991490003", displayValue: "ESLSCA Website" },
          { value: "991490004", displayValue: "Newspapers" },
          { value: "991490005", displayValue: "LinkedIn" },
          { value: "991490006", displayValue: "ESLSCA Students" },
          { value: "991490007", displayValue: "Facebook" },
          { value: "991490008", displayValue: "Billboards" },
          { value: "991490009", displayValue: "Other" },
        ],
        name: "eslsca_applicantsource",
      },
      value: "991490000",
    },
    eslsca_applicantsourceother: {
      elementType: "input",
      elementConfig: {
        type: "text",
        label: "Other",
        autoComplete: "Other",
        name: "eslsca_applicantsourceother",

        fullWidth: true,
      },
      maxLength: 100,
      icon: <AssignmentIcon style={{ color: "#959595" }} />,
      value: "",
    },
    _ses_certificationprogram_value: {
      elementType: "select",
      elementConfig: {
        label: "Programs*",
        options: [],
        name: "_ses_certificationprogram_value",
      },
      value: "",
    },
  },

  conatactInformation: {
    general: {
      emailaddress1: {
        elementType: "input",
        elementConfig: {
          type: "email",
          label: "Email Address",
          autoComplete: "email",
          name: "emailaddress1",
          required: true,
          fullWidth: true,
          disabled: true,
        },
        maxLength: 100,
        icon: <MailOutlineIcon style={{ color: "#959595" }} />,
        value: "",
      },
      emailaddress2: {
        elementType: "input",
        elementConfig: {
          type: "email",
          label: "Alternate Email Address",
          autoComplete: "email",
          name: "emailaddress2",
          fullWidth: true,
        },
        maxLength: 100,
        icon: <MailOutlineIcon style={{ color: "#959595" }} />,
        value: "",
      },
      mobilephone: {
        elementType: "mobile",
        selectFiledName: "countryCode",
        selectFiledValue: "",
        elementConfig: {
          type: "text",
          autoComplete: "mobile-phone",
          name: "mobilephone",
          required: true,
          // fullWidth: true,
        },
        maxLength: 50,
        isValid: false,
        errorMessage: "Mobile Phone can't be blank",
        icon: <PhoneIcon style={{ color: "#959595" }} />,
        value: "",
      },
    },

    homeAddress: {
      address1_line1: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "Street Address",
          autoComplete: "Street",
          name: "address1_line1",
          required: true,
          fullWidth: true,
        },
        maxLength: 250,
        isValid: false,
        errorMessage: "Street Address can't be blank",
        icon: <StreetviewIcon style={{ color: "#959595" }} />,
        value: "",
      },
      address1_city: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "City",
          autoComplete: "City",
          name: "address1_city",
          required: true,
          fullWidth: true,
        },
        maxLength: 80,
        isValid: false,
        errorMessage: "City can't be blank",
        icon: <LocationCityIcon style={{ color: "#959595" }} />,
        value: "",
      },
      eslsca_cairodistrictbusiness: {
        elementType: "select",
        elementConfig: {
          label: "Cairo District",
          options: [
            { value: "991490000", displayValue: "10th of Ramadan" },
            { value: "991490001", displayValue: "15th of May" },
            { value: "991490002", displayValue: "6th of October" },
            { value: "991490003", displayValue: "Abbasia" },
            { value: "991490004", displayValue: "Al-Darb Al-Ahmar" },
            { value: "991490005", displayValue: "Badr" },
            { value: "991490006", displayValue: "Boulaq" },
            { value: "991490007", displayValue: "Cairo" },
            { value: "991490008", displayValue: "Dokki" },
            { value: "991490009", displayValue: "Dreamland" },
            { value: "991490010", displayValue: "Elqobbah" },
            { value: "991490011", displayValue: "Elsakkakini" },
            { value: "991490012", displayValue: "First Settlement" },
            { value: "991490013", displayValue: "Fifth settlement" },
            { value: "991490014", displayValue: "Heliopolis" },
            { value: "991490015", displayValue: "Helwan" },
            { value: "991490016", displayValue: "Imbaba" },
            { value: "991490017", displayValue: "Kerdasa" },
            { value: "991490018", displayValue: "Madinaty" },
            { value: "991490019", displayValue: "Manshiyat Naser" },
            { value: "991490020", displayValue: "Manyal" },
            { value: "991490021", displayValue: "Marg" },
            { value: "991490022", displayValue: "Matareya" },
            { value: "991490023", displayValue: "Mit Okba" },
            { value: "991490024", displayValue: "Mohandessin" },
            { value: "991490025", displayValue: "Mokattam" },
            { value: "991490026", displayValue: "Nasr City" },
            { value: "991490027", displayValue: "New Cairo" },
            { value: "991490028", displayValue: "New Heliopolis" },
            { value: "991490029", displayValue: "Obour" },
            { value: "991490030", displayValue: "Old Cairo" },
            { value: "991490031", displayValue: "Qalyub" },
            { value: "991490032", displayValue: "Rob Elfarag" },
            { value: "991490033", displayValue: "Sheikh Zayed" },
            { value: "991490034", displayValue: "Shorouk" },
            { value: "991490035", displayValue: "Shubra" },
            { value: "991490036", displayValue: "Shubra Elkheima" },
            { value: "991490037", displayValue: "Zamalek" },
          ],
          name: "eslsca_cairodistrictbusiness",
        },
        value: "991490012",
      },
      address1_country: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "Country",
          autoComplete: "Country",
          name: "address1_country",
          required: true,
          fullWidth: true,
        },
        maxLength: 80,
        isValid: false,
        errorMessage: "Country can't be blank",
        icon: <PublicIcon style={{ color: "#959595" }} />,
        value: "",
      },
      address1_postalcode: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "Zip Code/Postal Code",
          autoComplete: "Zip Code/Postal Code",
          name: "address1_postalcode",
          fullWidth: true,
        },
        maxLength: 20,
        icon: <AddLocationIcon style={{ color: "#959595" }} />,
        value: "",
      },
    },
    workAddress: {
      address2_line1: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "Street Address",
          autoComplete: "Street-Address",
          name: "address2_line1",
          fullWidth: true,
        },
        maxLength: 100,
        icon: <StreetviewIcon style={{ color: "#959595" }} />,
        value: "",
      },
      address2_city: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "City",
          autoComplete: "city",
          name: "address2_city",
          fullWidth: true,
        },
        maxLength: 80,
        icon: <LocationCityIcon style={{ color: "#959595" }} />,
        value: "",
      },
      eslsca_cairodistrictresidential: {
        elementType: "select",
        elementConfig: {
          label: "Cairo District",
          options: [
            { value: "991490000", displayValue: "10th of Ramadan" },
            { value: "991490001", displayValue: "15th of May" },
            { value: "991490002", displayValue: "6th of October" },
            { value: "991490003", displayValue: "Abbasia" },
            { value: "991490004", displayValue: "Al-Darb Al-Ahmar" },
            { value: "991490005", displayValue: "Badr" },
            { value: "991490006", displayValue: "Boulaq" },
            { value: "991490007", displayValue: "Cairo" },
            { value: "991490008", displayValue: "Dokki" },
            { value: "991490009", displayValue: "Dreamland" },
            { value: "991490010", displayValue: "Elqobbah" },
            { value: "991490011", displayValue: "Elsakkakini" },
            { value: "991490012", displayValue: "First Settlement" },
            { value: "991490013", displayValue: "Fifth settlement" },
            { value: "991490014", displayValue: "Heliopolis" },
            { value: "991490015", displayValue: "Helwan" },
            { value: "991490016", displayValue: "Imbaba" },
            { value: "991490017", displayValue: "Kerdasa" },
            { value: "991490018", displayValue: "Madinaty" },
            { value: "991490019", displayValue: "Manshiyat Naser" },
            { value: "991490020", displayValue: "Manyal" },
            { value: "991490021", displayValue: "Marg" },
            { value: "991490022", displayValue: "Matareya" },
            { value: "991490023", displayValue: "Mit Okba" },
            { value: "991490024", displayValue: "Mohandessin" },
            { value: "991490025", displayValue: "Mokattam" },
            { value: "991490026", displayValue: "Nasr City" },
            { value: "991490027", displayValue: "New Cairo" },
            { value: "991490028", displayValue: "New Heliopolis" },
            { value: "991490029", displayValue: "Obour" },
            { value: "991490030", displayValue: "Old Cairo" },
            { value: "991490031", displayValue: "Qalyub" },
            { value: "991490032", displayValue: "Rob Elfarag" },
            { value: "991490033", displayValue: "Sheikh Zayed" },
            { value: "991490034", displayValue: "Shorouk" },
            { value: "991490035", displayValue: "Shubra" },
            { value: "991490036", displayValue: "Shubra Elkheima" },
            { value: "991490037", displayValue: "Zamalek" },
          ],
          name: "eslsca_cairodistrictresidential",
        },
        value: "991490001",
      },
      address2_country: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "Country",
          autoComplete: "Country",
          name: "address2_country",
          fullWidth: true,
        },
        maxLength: 80,
        icon: <PublicIcon style={{ color: "#959595" }} />,
        value: "",
      },
      address2_postalcode: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "Postal Code",
          autoComplete: "Postal-Code",
          name: "address2_postalcode",
          fullWidth: true,
        },
        maxLength: 20,
        icon: <AddLocationIcon style={{ color: "#959595" }} />,
        value: "",
      },
    },
    legal: {
      gurd_firstname: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "First Name",
          autoComplete: "first-name",
          name: "gurd_firstname",
          required: true,
          fullWidth: true,
        },
        maxLength: 50,
        isValid: false,
        errorMessage: "firstname can't be blank",
        icon: <AccountBoxIcon style={{ color: "#959595" }} />,
        value: "",
      },
      gurd_middlename: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "Middle Name",
          autoComplete: "middle-name",
          name: "gurd_middlename",
          fullWidth: true,
        },
        maxLength: 50,
        icon: <AccountBoxIcon style={{ color: "#959595" }} />,
        value: "",
      },
      gurd_lastname: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "Last Name",
          autoComplete: "last-name",
          name: "gurd_lastname",
          required: true,
          fullWidth: true,
        },
        maxLength: 50,
        isValid: false,
        errorMessage: "lastname can't be blank",
        icon: <AccountBoxIcon style={{ color: "#959595" }} />,
        value: "",
      },
      gurd_birthdate: {
        elementType: "date",
        elementConfig: {
          label: "Date of Birth (DD/MM/YYYY)",
          name: "gurd_birthdate",
          id: "time-picker",
          fullWidth: true,
        },
        value: "",
      },
      gurd_ses_nationality: {
        elementType: "select",
        elementConfig: {
          label: "Nationality*",
          options: Country,
          name: "gurd_ses_nationality",
        },
        value: 239,
      },
      gurd_address1_line1: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "Street",
          autoComplete: "Street",
          name: "gurd_address1_line1",
          required: true,
          fullWidth: true,
        },
        maxLength: 250,
        isValid: false,
        errorMessage: "Street can't be blank",
        icon: <StreetviewIcon style={{ color: "#959595" }} />,
        value: "",
      },
      gurd_address1_city: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "City",
          autoComplete: "City",
          name: "gurd_address1_city",
          required: true,
          fullWidth: true,
        },
        maxLength: 80,
        isValid: false,
        errorMessage: "City can't be blank",
        icon: <LocationCityIcon style={{ color: "#959595" }} />,
        value: "",
      },
      gurd_address1_country: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "Country",
          autoComplete: "Country",
          name: "gurd_address1_country",
          required: true,
          fullWidth: true,
        },
        maxLength: 80,
        isValid: false,
        errorMessage: "Country can't be blank",
        icon: <PublicIcon style={{ color: "#959595" }} />,
        value: "",
      },
      gurd_address1_postalcode: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "Zip Code/Postal Code",
          autoComplete: "Zip Code/Postal Code",
          name: "gurd_address1_postalcode",
          fullWidth: true,
        },
        maxLength: 20,
        icon: <AddLocationIcon style={{ color: "#959595" }} />,
        value: "",
      },
      gurd_emailaddress1: {
        elementType: "input",
        elementConfig: {
          type: "email",
          label: "Email Address",
          autoComplete: "email",
          name: "gurd_emailaddress1",
          required: true,
          fullWidth: true,
        },
        maxLength: 100,
        isValid: false,
        errorMessage: "Email Address can't be blank",
        icon: <MailOutlineIcon style={{ color: "#959595" }} />,
        value: "",
      },
      ses_relationship: {
        elementType: "select",
        elementConfig: {
          label: "Relationship with Legal Guardian *",
          options: [
            { value: 284210000, displayValue: "Father" },
            { value: 284210001, displayValue: "Mother" },
            { value: 284210002, displayValue: "Guardian" },
          ],
          name: "ses_relationship",
        },
        value: "",
      },
      gurd_mobilephone: {
        elementType: "mobile",
        elementConfig: {
          type: "text",
          name: "gurd_mobilephone",
          required: true,
          fullWidth: true,
        },
        maxLength: 50,
        isValid: false,
        errorMessage: "Mobile Phone Number can't be blank",
        icon: <PhoneIcon style={{ color: "#959595" }} />,
        value: "",
      },
    },
  },
  education: {
    Undergraduate: {
      ses_previousschool: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "Secondary School",
          autoComplete: "Secondary-School",
          name: "ses_previousschool",
          required: true,
          fullWidth: true,
        },
        maxLength: 100,
        isValid: false,
        errorMessage: "Secondary School can't be blank",
        icon: <SchoolIcon style={{ color: "#959595" }} />,
        value: "",
      },
      // ses_city: {
      //   elementType: "input",
      //   elementConfig: {
      //     type: "text",
      //     label: "City",
      //     autoComplete: "City",
      //     name: "ses_city",
      //     required: true,
      //     fullWidth: true,
      //   },
      //   maxLength: 100,
      //   isValid: false,
      //   errorMessage: "City can't be blank",
      //   icon: <LocationCityIcon style={{ color: "#959595" }} />,
      //   value: "",
      // },
      ses_country: {
        elementType: "select",
        elementConfig: {
          label: "Country*",
          options: SchoolCoutry,
          name: "ses_country",
        },
        value: "",
      },
      ses_graduationyear: {
        elementType: "select",
        elementConfig: {
          label: "Graduation Year*",
          options: YearList,
          name: "ses_graduationyear",
        },
        value: 2020,
      },
      ses_schoolcontact: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "Faculty",
          autoComplete: "Faculty",
          name: "ses_schoolcontact",
          required: true,
          fullWidth: true,
        },
        maxLength: 30,
        isValid: false,
        errorMessage: "Faculty can't be blank",
        icon: <SchoolIcon style={{ color: "#959595" }} />,
        value: "",
      },
      eslsca_primaryteachinglanguage: {
        elementType: "select",
        elementConfig: {
          label: "Primary Language*",
          options: [
            { value: 991490000, displayValue: "Arabic" },
            { value: 991490001, displayValue: "English" },
            { value: 991490002, displayValue: "German" },
            { value: 991490003, displayValue: "French" },
          ],
          name: "eslsca_primaryteachinglanguage",
        },
        value: "",
      },
      _ses_track_value: {
        elementType: "select",
        elementConfig: {
          label: "Preferred Major*",
          options: [],
          name: "_ses_track_value",
        },
        value: "",
      },
      _eslsca_startingacademicyearundergraduate_value: {
        elementType: "select",
        elementConfig: {
          label: "Academic Year*",
          options: [],
          name: "_eslsca_startingacademicyearundergraduate_value",
        },
        value: "",
      },
      eslsca_startingsemesterundergraduate: {
        elementType: "select",
        elementConfig: {
          label: "Academic Semester*",
          options: [
            { value: 991490000, displayValue: "1" },
            { value: 991490001, displayValue: "2" },
          ],
          name: "eslsca_startingsemesterundergraduate",
        },
        value: 991490001,
      },
      // eslsca_primaryteachinglanguage: {
      //   elementType: "select",
      //   elementConfig: {
      //     label: "Primary Teaching Language*",
      //     options: [
      //       { value: 991490000, displayValue: "1" },
      //       { value: 991490001, displayValue: "2" },
      //     ],
      //     name: "eslsca_primaryteachinglanguage",
      //   },
      //   value: 991490001,
      // },
      eslsca_schoolcertificate: {
        elementType: "select",
        elementConfig: {
          label: "Secondary School Certificate*",
          options: [
            { value: 991490000, displayValue: "Thanaweya Amma" },
            { value: 991490001, displayValue: "American Diploma" },
            { value: 991490002, displayValue: "French Baccalaureate" },
            { value: 991490003, displayValue: "IGSCE" },
            { value: 991490004, displayValue: "International Baccalaureate" },
            { value: 991490005, displayValue: "Abitur" },
            { value: 991490006, displayValue: "Canadian Baccalaureate" },
            { value: 991490007, displayValue: "Other" },
          ],
          name: "eslsca_schoolcertificate",
        },
        value: 991490001,
      },
      ses_certificateearned: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "Other Certificate",
          autoComplete: "Other Certificate",
          name: "ses_certificateearned",
          fullWidth: true,
        },
        maxLength: 100,
        icon: <CardGiftcardIcon style={{ color: "#959595" }} />,
        value: "",
      },
      eslsca_transfer: {
        elementType: "select",
        elementConfig: {
          label: "Are you transferring ?",
          options: [
            { value: true, displayValue: "Yes" },
            { value: false, displayValue: "No" },
          ],
          name: "eslsca_transfer",
        },
        value: "",
      },
      eslsca_transferfacultyorprogram: {
        elementType: "input",
        elementConfig: {
          type: "text",
          label: "Current Faculty or Study Program",
          autoComplete: "Current-Faculty",
          name: "eslsca_transferfacultyorprogram",
          fullWidth: true,
        },
        maxLength: 100,
        icon: <AssignmentIcon style={{ color: "#959595" }} />,
        value: "",
      },
      eslsca_semesternumberfortransfer: {
        elementType: "input",
        elementConfig: {
          type: "number",
          label: "Semester Number",
          autoComplete: "Semester-Number",
          name: "eslsca_semesternumberfortransfer",
          fullWidth: true,
        },
        maxLength: 100,
        icon: <SchoolIcon style={{ color: "#959595" }} />,
        value: "",
      },
    },
    graduate: {
      prevEducation: {
        ses_previousschool: {
          elementType: "input",
          elementConfig: {
            type: "text",
            label: "University",
            autoComplete: "University",
            name: "ses_previousschool",
            required: true,
            fullWidth: true,
          },
          maxLength: 100,
          isValid: false,
          errorMessage: "Secondary School can't be blank",
          icon: <SchoolIcon style={{ color: "#959595" }} />,
          value: "",
        },
        // ses_city: {
        //   elementType: "input",
        //   elementConfig: {
        //     type: "text",
        //     label: "City",
        //     autoComplete: "City",
        //     name: "ses_city",
        //     required: true,
        //     fullWidth: true,
        //   },
        //   maxLength: 100,
        //   isValid: false,
        //   errorMessage: "City can't be blank",
        //   icon: <LocationCityIcon style={{ color: "#959595" }} />,
        //   value: "",
        // },
        ses_country: {
          elementType: "select",
          elementConfig: {
            label: "Country*",
            options: SchoolCoutry,
            name: "ses_country",
          },
          value: "",
        },
        ses_graduationyear: {
          elementType: "select",
          elementConfig: {
            label: "Graduation Year*",
            options: YearList,
            name: "ses_graduationyear",
          },
          value: 2020,
        },
        eslsca_businessdegree: {
          elementType: "select",
          elementConfig: {
            label: "Business Degree*",
            options: [
              { value: true, displayValue: "Yes" },
              { value: false, displayValue: "No" },
            ],
            name: "eslsca_businessdegree",
          },
          value: "",
        },
        // ses_major: {
        //   elementType: "input",
        //   elementConfig: {
        //     type: "text",
        //     label: "Major Business Degree",
        //     autoComplete: "Major",
        //     name: "ses_major",
        //     required: true,
        //     fullWidth: true,
        //   },
        //   maxLength: 30,
        //   isValid: false,
        //   errorMessage: "Major Business Degree can't be blank",
        //   icon: <DnsIcon style={{ color: "#959595" }} />,
        //   value: "",
        // },
        eslsca_gpa: {
          elementType: "input",
          elementConfig: {
            type: "number",
            label: "GPA",
            autoComplete: "GPA",
            name: "eslsca_gpa",
            required: true,
            fullWidth: true,
          },
          maxLength: 30,
          isValid: false,
          errorMessage: "GPA can't be blank",
          icon: <SchoolIcon style={{ color: "#959595" }} />,
          value: "",
        },
        ses_schoolcontact: {
          elementType: "input",
          elementConfig: {
            type: "text",
            label: "Faculty",
            autoComplete: "Faculty",
            name: "ses_schoolcontact",
            required: true,
            fullWidth: true,
          },
          maxLength: 30,
          isValid: false,
          errorMessage: "Faculty can't be blank",
          icon: <SchoolIcon style={{ color: "#959595" }} />,
          value: "",
        },
      },

      prevEmployment: {
        ses_employer: {
          elementType: "input",
          elementConfig: {
            type: "text",
            label: "Company Name",
            autoComplete: "Company-Name",
            name: "ses_employer",
            required: true,
            fullWidth: true,
          },
          maxLength: 30,
          isValid: false,
          errorMessage: "Company Name can't be blank",
          icon: <BusinessIcon style={{ color: "#959595" }} />,
          value: "",
        },
        ses_previousemployment: {
          elementType: "input",
          elementConfig: {
            type: "text",
            label: "Job Title",
            autoComplete: "Job-Title",
            name: "ses_previousemployment",
            required: true,
            fullWidth: true,
          },
          maxLength: 30,
          isValid: false,
          errorMessage: "Job Title can't be blank",
          icon: <WorkIcon style={{ color: "#959595" }} />,
          value: "",
        },
        ses_startdate: {
          elementType: "exactDate",
          elementConfig: {
            label: "Hiring Date* (DD/MM/YYYY)",
            name: "ses_startdate",
            id: "time-picker",
            fullWidth: true,
          },
          value: "",
        },
        eslsca_yearsofrelevantexperience: {
          elementType: "input",
          elementConfig: {
            type: "text",
            label: "Total Years of Relevant Experience",
            autoComplete: "Job-Title",
            name: "eslsca_yearsofrelevantexperience",
            required: true,
            fullWidth: true,
          },
          maxLength: 30,
          isValid: false,
          errorMessage: "Total Years of Relevant Experience can't be blank",
          icon: <WorkIcon style={{ color: "#959595" }} />,
          value: "",
        },
      },
      attendanceJoiningDate: {
        _eslsca_startingacademicyeargraduate_value: {
          elementType: "select",
          elementConfig: {
            label: "Academic Year*",
            options: [],
            name: "_eslsca_startingacademicyeargraduate_value",
          },
          value: "",
        },
        eslsca_startingsemestergraduate: {
          elementType: "select",
          elementConfig: {
            label: "Academic Semester*",
            options: [
              { value: 991490000, displayValue: "Fall" },
              { value: 991490001, displayValue: "Winter" },
              { value: 991490002, displayValue: "Spring" },
            ],
            name: "eslsca_startingsemestergraduate",
          },
          value: 991490001,
        },
        _eslsca_firstattendancescheduleoption_value: {
          elementType: "select",
          elementConfig: {
            label: "First Attendance Schedule Choice*",
            options: [],
            name: "_eslsca_firstattendancescheduleoption_value",
          },
          value: 991490001,
        },
        _eslsca_seconattendancescheduleoption_value: {
          elementType: "select",
          elementConfig: {
            label: "Second Attendance Schedule Choice*",
            options: [],
            name: "_eslsca_seconattendancescheduleoption_value",
          },
          value: 991490001,
        },
        _eslsca_campus_value: {
          elementType: "select",
          elementConfig: {
            label: "Campus*",
            options: [],
            name: "_eslsca_campus_value",
          },
          value: "",
        },
      },

      // eslsca_businessdegree: {
      //   elementType: "select",
      //   elementConfig: {
      //     label: "Business Degree*",
      //     options: [
      //       { value: true, displayValue: "Yes" },
      //       { value: false, displayValue: "No" },
      //     ],
      //     name: "eslsca_businessdegree",
      //   },
      //   value: "",
      // },
    },
  },
  financialAid: {
    eslsca_applyforfinancialaid: {
      elementType: "select",
      elementConfig: {
        label: "Apply for Financial Aid ",
        options: [
          { value: true, displayValue: "Yes" },
          { value: false, displayValue: "No" },
        ],
        name: "eslsca_applyforfinancialaid",
      },
      value: false,
    },
    eslsca_scholarshiptype: {
      elementType: "select",
      elementConfig: {
        label: "Scholarship Type",
        options: [
          { value: 991490000, displayValue: "Academic Excellence" },
          { value: 991490001, displayValue: "Corporate" },
          { value: 991490002, displayValue: "Syndicate" },
          { value: 991490003, displayValue: "Other" },
          { value: 991490004, displayValue: "OUDA" },
        ],
        name: "eslsca_scholarshiptype",
      },
      value: undefined,
    },
    eslsca_otherscholarship: {
      elementType: "input",
      elementConfig: {
        type: "text",
        label: "Other Scholarship",
        autoComplete: "Other Scholarship",
        name: "eslsca_otherscholarship",
        fullWidth: true,
      },
      maxLength: 30,
      isValid: false,
      icon: <WorkIcon style={{ color: "#959595" }} />,
      value: "",
    },
    eslsca_siblingateslsca: {
      elementType: "select",
      elementConfig: {
        label: "Sibling at ESLSCA",
        options: [
          { value: true, displayValue: "Yes" },
          { value: false, displayValue: "No" },
        ],
        name: "eslsca_siblingateslsca",
      },
      value: undefined,
    },
    eslsca_siblingname: {
      elementType: "input",
      elementConfig: {
        type: "text",
        label: "Sibling Name",
        autoComplete: "Sibling Name",
        name: "eslsca_siblingname",
        fullWidth: true,
      },
      maxLength: 30,
      isValid: false,
      icon: <AccountBoxIcon style={{ color: "#959595" }} />,
      value: "",
    },
    eslsca_siblinguniversityid: {
      elementType: "input",
      elementConfig: {
        type: "text",
        label: "Sibling University ID",
        autoComplete: "Sibling University ID",
        name: "eslsca_siblinguniversityid",
        fullWidth: true,
      },
      maxLength: 30,
      isValid: false,
      icon: <SchoolIcon style={{ color: "#959595" }} />,
      value: "",
    },
  },
  applicationFee: {},
  agreeSign: {
    eslsca_accepttermsanddonditions: {
      elementType: "checkbox",
      elementConfig: {
        label:
          "By checking the “I accept” you hereby agree to all the points mentioned in the terms and conditions agreement, these terms govern your relationship with ESLSCA university, and are subject to change at any time without prior notification, it is your responsibility to stay updated with any changes made.",
        name: "eslsca_accepttermsanddonditions",
      },
      value: false,
    },
    eslsca_esignature: {
      elementType: "input",
      elementConfig: {
        type: "text",
        label: "Type your name as an e-Signature",
        autoComplete: "e-Signature",
        name: "eslsca_esignature",
        required: true,
        fullWidth: true,
      },
      maxLength: 20,
      isValid: false,
      errorMessage: "e-Signature can't be blank",
      icon: <AssignmentIcon style={{ color: "#959595" }} />,
      value: "",
    },
  },
  emergenencyContact: {
    // name: {
    //   elementType: "input",
    //   elementConfig: {
    //     type: "text",
    //     label: "Name",
    //     autoComplete: "name",
    //     name: "name",
    //     required: true,
    //     fullWidth: true,
    //   },
    //   icon: <AccountBoxIcon style={{ color: "#959595" }} />,
    //   value: "",
    // },
    // relationship: {
    //   elementType: "input",
    //   elementConfig: {
    //     type: "text",
    //     label: "Relationship",
    //     autoComplete: "Relationship",
    //     name: "relationship",
    //     required: true,
    //     fullWidth: true,
    //   },
    //   icon: <TagFacesIcon style={{ color: "#959595" }} />,
    //   value: "",
    // },
    // phone: {
    //   elementType: "input",
    //   elementConfig: {
    //     type: "text",
    //     label: "Emergency contact phone",
    //     autoComplete: "mobile-phone",
    //     name: "phone",
    //     required: true,
    //     fullWidth: true,
    //   },
    //   icon: <PhoneIcon style={{ color: "#959595" }} />,
    //   value: "",
    // },
  },
  miscellanous: {
    // contactMode: {
    //   elementType: "select",
    //   elementConfig: {
    //     options: [
    //       { value: "Any", displayValue: "Any" },
    //       { value: "Email", displayValue: "Email" },
    //       { value: "phone", displayValue: "phone" },
    //       { value: "Fax", displayValue: "Fax" },
    //       { value: "Mail", displayValue: "Mail" },
    //     ],
    //     name: "contactMode",
    //   },
    //   value: "Any",
    // },
  },
};

export default FormData;
